//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MyPanel extends JPanel {
    private JLabel jcomp1;
    private JCheckBox multipleThreadsEnable;
    private JTextField numberOfThreads;
    private JLabel jcomp4;
    private JCheckBox fileSizeEnable;
    private JSlider fileSizeSelect;
    private JToggleButton startTestButton;
    private JPasswordField percOfProgram;
    private JLabel pathToTest;
    private JLabel jcomp10;
    private JTextField lopgInfoArea;
    private JCheckBox accept;

    public MyPanel() {
        //construct components
        jcomp1 = new JLabel ("File Transfer Tester - Kacper Kisielewski");
        multipleThreadsEnable = new JCheckBox ("Multiple Threads");
        numberOfThreads = new JTextField (5);
        jcomp4 = new JLabel ("Number of Threads");
        fileSizeEnable = new JCheckBox ("Specify size of file");
        fileSizeSelect = new JSlider (0, 50);
        startTestButton = new JToggleButton ("Start Test", false);
        percOfProgram = new JPasswordField (5);
        pathToTest = new JLabel ("Specify testing folder");
        jcomp10 = new JLabel ("logInfo");
        lopgInfoArea = new JTextField (5);
        accept = new JCheckBox ("");

        //set components properties
        numberOfThreads.setEnabled (false);
        fileSizeSelect.setOrientation (JSlider.HORIZONTAL);
        fileSizeSelect.setMinorTickSpacing (10);
        fileSizeSelect.setMajorTickSpacing (3);
        fileSizeSelect.setPaintTicks (true);
        fileSizeSelect.setPaintLabels (true);
        fileSizeSelect.setEnabled (false);
        fileSizeSelect.setToolTipText ("MB");
        startTestButton.setToolTipText ("Press Button to Start Test!");
        percOfProgram.setEnabled (false);
        percOfProgram.setToolTipText ("This field show only % of tasks.");
        lopgInfoArea.setEnabled (false);
        lopgInfoArea.setToolTipText ("Information");
        accept.setToolTipText ("Accept the terms and risks");

        //adjust size and set layout
        setPreferredSize (new Dimension (321, 364));
        setLayout (null);

        //add components
        add (jcomp1);
        add (multipleThreadsEnable);
        add (numberOfThreads);
        add (jcomp4);
        add (fileSizeEnable);
        add (fileSizeSelect);
        add (startTestButton);
        add (percOfProgram);
        add (pathToTest);
        add (jcomp10);
        add (lopgInfoArea);
        add (accept);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (40, 5, 240, 20);
        multipleThreadsEnable.setBounds (0, 35, 135, 20);
        numberOfThreads.setBounds (180, 60, 100, 25);
        jcomp4.setBounds (60, 60, 120, 25);
        fileSizeEnable.setBounds (0, 90, 150, 20);
        fileSizeSelect.setBounds (5, 110, 315, 60);
        startTestButton.setBounds (15, 300, 165, 25);
        percOfProgram.setBounds (185, 300, 100, 25);
        pathToTest.setBounds (5, 165, 130, 25);
        jcomp10.setBounds (10, 330, 45, 25);
        lopgInfoArea.setBounds (55, 330, 230, 25);
        accept.setBounds (295, 315, 20, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MyPanel());
        frame.pack();
        frame.setVisible (true);
    }
}
